const colortypes = [
  {"type" :"normal", "color" : '#A8A878'},
  {"type" :"fighting" , "color" :  '#C03028'},
  {"type" :"flying" , "color" :  '#A890F0'},
  {"type" :"poison" , "color" :  '#A040A0'},
  {"type" :"ground" , "color" :  '#E0C068'},
  {"type" :"rock" , "color" :  '#B8A038'},
  {"type" :"bug" , "color" :  '#A8B820'},
  {"type" :"ghost" , "color" :  '#705898'},
  {"type" :"steel" , "color" :  '#B8B8D0'},
  {"type" :"fire" , "color" :  '#fa9223'},
  {"type" :"water" , "color" :  '#789df5'},
  {"type" :"grass" , "color" :  '#42d481'},
  {"type" :"electric" , "color" :  '#FFCE4B'},
  {"type" :"psychic" , "color" :  '#F85888'},
  {"type" :"ice" , "color" :  '#98D8D8'},
  {"type" :"dragon" , "color" :  '#7038F8'},
  {"type" :"dark" , "color" :  '#705848'},
  {"type" :"fairy" , "color" : '#EE99AC'}];